name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync LeetCode Solutions
        uses: xidongw/leetcode-sync-plus@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          # The '$' is placed outside the braces to stop GitHub from throwing an error
          output-file-path: 'solutions/$`{{ difficulty }}`/$`{{ id }}`-$`{{ titleSlug }}`.$`{{ ext }}`'
